[tox]
distribute = False
envlist =
    py{39,310,311,312}-dj42{-svg,}
    py{310,311,312,313,314}-dj52{-svg,}
    py{312,313,314}-dj60{-svg,}
    docs
skip_missing_interpreters = True

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE=tests.settings
    PYTHONPATH={toxinidir}
uv_python_preference = managed
usedevelop = True
extras =
    svg: svg
deps =
    dj42: django~=4.2
    dj52: django~=5.2
    dj60: django~=6.0
    testfixtures
    pytest
    pytest-cov
    pytest-django
    coverage[toml]
commands =
    python -Wd -m pytest {posargs}
ignore_outcome =
    djangomain: true

[testenv:py314-dj52-svg]
commands =
    python -Wd -m pytest --cov easy_thumbnails --cov-context test {posargs}

[testenv:docs]
basepython = python3.14
usedevelop = True
deps =
    -r docs/requirements.txt
commands =
    sphinx-build -b html docs docs/_build/html
